spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

keycloak:
  realm: priam-realm
  resource: Data-client
  bearer-only: true
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  ssl-required: none
  cors: true


server:
  port: 8090